language: node_js
repo_token: O9S1H0OrNj1QkJdG75C1xdDyQFH1ysw75
node_js:
  - '5'
  - '4'
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - github.com
before_install:
- openssl aes-256-cbc -K $encrypted_8281a8241ab5_key -iv $encrypted_8281a8241ab5_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "snakeliwei"
- git config --global user.email snakeliwei@gmail.com
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo g
- hexo d
