# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lyndon Li's Blog
subtitle: From tester to Full-stack
description:
author: Lyndon Li
email: panjiabang@gmail.com
avatar: //i.imgur.com/s4Jxv8Y.png
author_title: 'Test Engineer & Web Developer'
location: 'Hubei, China'
follow: https://github.com/snakeliwei/
language: en
github_repo: https://github.com/snakeliwei/Myblog-src

stylus:
  compress: true

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://snakeliwei.github.io
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Links
links:
  刘典的博客: http://blog.sina.com.cn/ld2254432
  StartupNews: http://news.dbanotes.net/news
  Cubernet's Blog: http://cubernet.cn

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
post_asset_folder: false
relative_link: false
highlight:
  enable: false
  line_number: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 2


apple_icon_57: //i.imgur.com/mV0lQ6M.jpg
apple_icon_72: //i.imgur.com/3D3m65B.jpg
apple_icon_76: //i.imgur.com/gg9PfXZ.jpg
apple_icon_114: //i.imgur.com/vak90qc.jpg
apple_icon_120: //i.imgur.com/RL6jkBf.jpg
apple_icon_152: //i.imgur.com/KWYY0nb.jpg


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: lyndonsblog
google_analytics: UA-71216232-1

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus


exclude_generator:

since: 2015

plugins:


markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: false
    quotes: '“”‘’'
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ''

html_minifier:
  exclude:
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:snakeliwei/snakeliwei.github.com.git
  branch: master
